/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as Login01RouteImport } from './routes/login/01'
import { Route as Login02RouteImport } from './routes/login/02'
import { Route as Login03RouteImport } from './routes/login/03'
import { Route as Login04RouteImport } from './routes/login/04'
import { Route as Login05RouteImport } from './routes/login/05'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/_authed/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const Login01Route = Login01RouteImport.update({
  id: '/login/01',
  path: '/login/01',
  getParentRoute: () => rootRouteImport,
} as any)
const Login02Route = Login02RouteImport.update({
  id: '/login/02',
  path: '/login/02',
  getParentRoute: () => rootRouteImport,
} as any)
const Login03Route = Login03RouteImport.update({
  id: '/login/03',
  path: '/login/03',
  getParentRoute: () => rootRouteImport,
} as any)
const Login04Route = Login04RouteImport.update({
  id: '/login/04',
  path: '/login/04',
  getParentRoute: () => rootRouteImport,
} as any)
const Login05Route = Login05RouteImport.update({
  id: '/login/05',
  path: '/login/05',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/login/01': typeof Login01Route
  '/login/02': typeof Login02Route
  '/login/03': typeof Login03Route
  '/login/04': typeof Login04Route
  '/login/05': typeof Login05Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/login/01': typeof Login01Route
  '/login/02': typeof Login02Route
  '/login/03': typeof Login03Route
  '/login/04': typeof Login04Route
  '/login/05': typeof Login05Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/login/01': typeof Login01Route
  '/login/02': typeof Login02Route
  '/login/03': typeof Login03Route
  '/login/04': typeof Login04Route
  '/login/05': typeof Login05Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login/01'
    | '/login/02'
    | '/login/03'
    | '/login/04'
    | '/login/05'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login/01'
    | '/login/02'
    | '/login/03'
    | '/login/04'
    | '/login/05'
  id:
    | '__root__'
    | '/'
    | '/_authed/dashboard'
    | '/login/01'
    | '/login/02'
    | '/login/03'
    | '/login/04'
    | '/login/05'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  Login01Route: typeof Login01Route
  Login02Route: typeof Login02Route
  Login03Route: typeof Login03Route
  Login04Route: typeof Login04Route
  Login05Route: typeof Login05Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/01': {
      id: '/login/01'
      path: '/login/01'
      fullPath: '/login/01'
      preLoaderRoute: typeof Login01RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/02': {
      id: '/login/02'
      path: '/login/02'
      fullPath: '/login/02'
      preLoaderRoute: typeof Login02RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/03': {
      id: '/login/03'
      path: '/login/03'
      fullPath: '/login/03'
      preLoaderRoute: typeof Login03RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/04': {
      id: '/login/04'
      path: '/login/04'
      fullPath: '/login/04'
      preLoaderRoute: typeof Login04RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/05': {
      id: '/login/05'
      path: '/login/05'
      fullPath: '/login/05'
      preLoaderRoute: typeof Login05RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  Login01Route: Login01Route,
  Login02Route: Login02Route,
  Login03Route: Login03Route,
  Login04Route: Login04Route,
  Login05Route: Login05Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
